### ISSUE TITLE
This doesn’t exist

### ISSUE THREAD

**Issue by DuckMasterAl** [discordextremelist/del.py#1]
Read the title...

**Comment by carolinaisslaying** [comment]
get you or moksej to make it idk lmfao

**Comment by carolinaisslaying** [comment]
tbh I could probably just make it myself

**Comment by DuckMasterAl** [comment]
Cool, it still doesn't exist

**Comment by DuckMasterAl** [comment]
but... it still doesn't exist 👀

**Comment by TheMoksej** [comment]
> but... it still doesn't exist 👀

are you sure about that _cough cough_

**Comment by DuckMasterAl** [comment]
> > but... it still doesn't exist 👀
> 
> are you sure about that _cough cough_

Yep 
<img width="918" alt="Screen Shot 2020-11-22 at 12 10 11 PM" src="https://user-images.githubusercontent.com/43557963/99910389-ae514400-2cbb-11eb-9638-bfd1e5171e12.png">
